version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: environment.yml

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py

